# Generated by Django 4.0.6 on 2022-08-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=100)),
                ('nim', models.IntegerField(default=0)),
                ('message', models.TextField()),
            ],
        ),
    ]
